// @ts-nocheck -- translated goal-card JSX is isolated; persistence types remain enforced in lib/goals.ts.
import { FormEvent, useEffect, useState } from 'react'
import { CalendarDays, Check, CircleDollarSign, Edit3, Flag, HeartPulse, Leaf, Plus, Sparkles, Target, Trash2, UserRound, X } from 'lucide-react'
import { getText, Language } from '../i18n'
import { Goal, GoalCategory, GoalStatus, listGoals, removeGoal, saveGoal } from '../lib/goals'

type Props = { language: Language, userId: string, premium: boolean, currency: string, onUpgrade: () => void }
const categoryIcons={financial:CircleDollarSign,recovery:Leaf,health:HeartPulse,personal:UserRound,custom:Target}

export default function GoalsPage({language,userId,premium,currency,onUpgrade}:Props){
  const t=getText(language)
  const [goals,setGoals]=useState<Goal[]>([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Goal|null>(null)
  const [modal,setModal]=useState(false),[feedback,setFeedback]=useState(''),[error,setError]=useState(''),[formCategory,setFormCategory]=useState<GoalCategory>('recovery')
  const locale=language==='pt'?'pt-BR':language==='es'?'es-ES':'en-US'
  const formatMoney=(value:number)=>new Intl.NumberFormat(locale,{style:'currency',currency,maximumFractionDigits:2}).format(value)
  const currencySymbol=new Intl.NumberFormat(locale,{style:'currency',currency,currencyDisplay:'narrowSymbol'}).formatToParts(0).find(part=>part.type==='currency')?.value
  const refresh=async()=>{setLoading(true);try{setGoals(await listGoals(userId))}catch(reason){setError(reason instanceof Error?reason.message:t.goalsError)}finally{setLoading(false)}}
  useEffect(()=>{refresh()},[userId])
  const openNew=()=>{if(!premium&&goals.filter(goal=>goal.status!=='cancelled').length>=1){setError(t.freeGoalLimit);return}setEditing(null);setFormCategory('recovery');setModal(true);setError('')}
  const openEdit=(goal:Goal)=>{setEditing(goal);setFormCategory(goal.category);setModal(true);setError('')}
  const submit=async(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();setError('')
    const form=new FormData(event.currentTarget),title=String(form.get('title')).trim(),target=Number(form.get('target')),current=Number(form.get('current')),customName=String(form.get('custom_category_name')||'').trim()
    if(!title||target<0||current<0||(formCategory==='custom'&&!customName)){setError(t.goalValidation);return}
    try{await saveGoal(userId,{...editing,title,description:String(form.get('description')),category:formCategory,custom_category_name:customName||null,target_value:target,current_value:current,status:String(form.get('status')) as GoalStatus,deadline:String(form.get('deadline'))||null});setModal(false);setFeedback(t.goalSaved);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:t.goalsError)}
  }
  const complete=async(goal:Goal)=>{try{await saveGoal(userId,{...goal,status:'completed',current_value:goal.target_value,progress_percentage:100,completed_at:new Date().toISOString()});setFeedback(t.goalCompleted);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:t.goalsError)}}
  const remove=async(goal:Goal)=>{if(!confirm(t.deleteGoalConfirm))return;try{await removeGoal(userId,goal.id);setFeedback(t.goalDeleted);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:t.goalsError)}}
  return <div className="page goals-page">
    <section className="page-title"><div><span className="eyebrow"><Target size={14}/>{t.goalsEyebrow}</span><h1>{t.goalsTitle}</h1><p>{t.goalsSubtitle}</p></div><button className="primary" onClick={openNew}><Plus size={17}/>{t.newGoal}</button></section>
    {feedback&&<div className="goal-toast"><Check/>{feedback}<button onClick={()=>setFeedback('')}><X/></button></div>}
    {error&&<div className="form-error goals-error">{error}{!premium&&error===t.freeGoalLimit&&<button onClick={onUpgrade}>{t.upgrade}</button>}</div>}
    <div className="goals-summary"><article><span><Target/></span><div><strong>{goals.filter(g=>g.status!=='completed'&&g.status!=='cancelled').length}</strong><small>{t.activeGoals}</small></div></article><article><span><Check/></span><div><strong>{goals.filter(g=>g.status==='completed').length}</strong><small>{t.completedGoals}</small></div></article><article><span><Sparkles/></span><div><strong>{goals.length?Math.round(goals.reduce((sum,g)=>sum+g.progress_percentage,0)/goals.length):0}%</strong><small>{t.averageProgress}</small></div></article></div>
    {loading?<div className="goals-loading">{t.loadingGoals}</div>:goals.length===0?<section className="empty-goals"><span><Flag/></span><h2>{t.noGoals}</h2><p>{t.noGoalsSub}</p><button className="primary" onClick={openNew}><Plus/>{t.createFirstGoal}</button></section>:<section className="goals-grid">{goals.map(goal=>{
      const Icon=categoryIcons[goal.category],categoryName=goal.category==='custom'&&goal.custom_category_name?goal.custom_category_name:t[goal.category]
      return <article className={`goal-detail-card ${goal.status==='completed'?'completed':''}`} key={goal.id}><header><span className={`goal-category-icon ${goal.category}`}><Icon/></span><div><small>{categoryName}</small><span className={`goal-status ${goal.status}`}>{t[goal.status]}</span></div><div className="goal-card-actions"><button aria-label={t.editGoal} onClick={()=>openEdit(goal)}><Edit3/></button><button aria-label={t.deleteGoal} onClick={()=>remove(goal)}><Trash2/></button></div></header><h2>{goal.title}</h2><p>{goal.description}</p><div className="goal-progress-meta"><span>{t.progress}</span><strong>{goal.progress_percentage}%</strong></div><div className="goal-detail-progress"><i style={{width:`${goal.progress_percentage}%`}}/></div><div className="goal-values"><span><b>{goal.category==='financial'?formatMoney(goal.current_value):goal.current_value}</b> / {goal.category==='financial'?formatMoney(goal.target_value):goal.target_value}</span>{goal.deadline&&<time><CalendarDays/>{new Intl.DateTimeFormat(locale).format(new Date(`${goal.deadline}T12:00:00`))}</time>}</div>{goal.status!=='completed'&&<button className="complete-goal" onClick={()=>complete(goal)}><Check/>{t.markCompleted}</button>}</article>
    })}</section>}
    {modal&&<div className="modal-backdrop"><form className="simple-modal goal-modal" onSubmit={submit}><header><h2>{editing?t.editGoal:t.newGoal}</h2><button type="button" className="icon-button" aria-label={t.close} onClick={()=>setModal(false)}><X/></button></header><label>{t.goalTitleLabel}<input name="title" defaultValue={editing?.title} required placeholder={t.goalTitlePlaceholder}/></label><label>{t.description}<textarea name="description" defaultValue={editing?.description} placeholder={t.goalDescriptionPlaceholder}/></label><div className="goal-form-grid"><label>{t.category}<select name="category" value={formCategory} onChange={event=>setFormCategory(event.target.value as GoalCategory)}>{(['financial','recovery','health','personal','custom'] as GoalCategory[]).map(value=><option value={value} key={value}>{t[value]}</option>)}</select></label><label>{t.status}<select name="status" defaultValue={editing?.status||'not_started'}>{(['not_started','in_progress','completed','cancelled'] as GoalStatus[]).map(value=><option value={value} key={value}>{t[value]}</option>)}</select></label>{formCategory==='custom'&&<label className="field-wide">{t.customCategoryName}<input name="custom_category_name" defaultValue={editing?.custom_category_name||''} required placeholder={t.customCategoryPlaceholder}/></label>}<label>{t.currentValue}<div className={formCategory==='financial'?'currency-input':''}>{formCategory==='financial'&&<span>{currencySymbol}</span>}<input name="current" type="number" min="0" step="0.01" defaultValue={editing?.current_value||0}/></div></label><label>{t.targetValue}<div className={formCategory==='financial'?'currency-input':''}>{formCategory==='financial'&&<span>{currencySymbol}</span>}<input name="target" type="number" min="0" step="0.01" defaultValue={editing?.target_value||30}/></div></label><label className="field-wide">{t.deadline}<input name="deadline" type="date" defaultValue={editing?.deadline||''}/></label></div><button className="primary wide" type="submit">{t.saveGoal}</button></form></div>}
  </div>
}
